@startuml A1 Прием и регистрация (Неавтоматизированная)

title IDEF0 Диаграмма A1 (Неавтоматизированная версия)\nПрием и регистрация студентов

rectangle "Прием\nзаявлений\n\nA11" as A11
rectangle "Проверка\nдокументов\n\nA12" as A12
rectangle "Медицинское\nосвидетельствование\n\nA13" as A13
rectangle "Зачисление\nв школу\n\nA14" as A14

' Входы - максимум 3
[Заявки на обучение] -right-> A11
[Документы] -right-> A11

' Потоки между процессами
A11 -right-> A12 : Анкеты\nкандидатов
A12 -right-> A13 : Проверенные\nдокументы
A13 -right-> A14 : Прошедшие\nмедосмотр

' Управление - максимум 4
[Правила приема] -down-> A11
[Медицинские стандарты] -down-> A13
[Правила зачисления] -down-> A14

' Выходы - максимум 4
A14 -right-> [Зачисленные студенты]
A14 -down-> [Личные дела]

' Механизмы - максимум 5
[Приемная комиссия] -up-> A11
[Специалист по документам] -up-> A12
[Врачи + Оборудование] -up-> A13
[Администрация] -up-> A14

@enduml
