@startuml A2 Планирование обучения (Неавтоматизированная)

title IDEF0 Диаграмма A2 (Неавтоматизированная версия)\nПланирование обучения

rectangle "Формирование\nучебных групп\n\nA21" as A21
rectangle "Составление\nрасписания\n\nA22" as A22
rectangle "Назначение\nинструкторов\n\nA23" as A23
rectangle "Резервирование\nресурсов\n\nA24" as A24

' Входы - максимум 3
[Зачисленные студенты] -right-> A21

' Потоки между процессами
A21 -right-> A22 : Учебные\nгруппы
A22 -right-> A23 : Черновик\nрасписания
A23 -right-> A24 : Расписание с\nинструкторами

' Управление - максимум 4
[Учебный план] -down-> A22
[Квалификация инструкторов] -down-> A23
[Регламент ТО] -down-> A24

' Выходы - максимум 4
A24 -right-> [Утвержденное расписание]
A24 -down-> [График ресурсов]

' Механизмы - максимум 5
[Методисты] -up-> A21
[Планировщики] -up-> A22
[Руководитель учебного отдела] -up-> A23
[Техотдел] -up-> A24

@enduml
