@startuml A5 Выдача сертификатов (Автоматизированная)

title IDEF0 Диаграмма A5 (Автоматизированная версия)\nВыдача сертификатов

rectangle "Проверка\nзавершения\nпрограммы\n\nA51" as A51
rectangle "Формирование\nсертификата\n\nA52" as A52
rectangle "Регистрация\nв реестре\n\nA53" as A53
rectangle "Выдача\nдокумента\n\nA54" as A54

' Входы - те же что в A0 для процесса A5
[Результаты аттестации] -right-> A51

' Потоки между процессами
A51 -right-> A52 : Данные\nвыпускника
A52 -right-> A53 : Готовый\nсертификат
A53 -right-> A54 : Зарегистрированный\nсертификат

' Управление - те же что в A0 для процесса A5
[Стандарты обучения] -down-> A51
[Стандарты обучения] -down-> A52

' Выходы
A54 -right-> [Сертифицированные пилоты]

' Механизмы - те же что в A0 для процесса A5
[АИС "Летная школа"] -up-> A51
[АИС "Летная школа"] -up-> A52
[АИС "Летная школа"] -up-> A53
[Персонал] -up-> A54

@enduml
